# Check for an interactive session
[ -z "$PS1" ] && return

source /etc/profile

source ~/.bash/options
source ~/.bash/aliases
source ~/.bash/env

for function in ~/.bash/functions/*.sh; do
    source "$function"
done

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Perlbrew setup
export PERLBREW_ROOT=~/.perl5/perlbrew
[[ -s "$HOME/.perl5/perlbrew/etc/bashrc" ]] && source "$HOME/.perl5/perlbrew/etc/bashrc"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
